#!/usr/bin/env bash
# Configure localhost and facebook.com in the hosts file.
sed -i 's/127\.0\.0\.1/127.0.0.2/g' /etc/hosts
sed -i '/facebook\.com/d' /etc/hosts
echo "8.8.8.8 facebook.com" >> /etc/hosts
